#!/usr/bin/env python3
"""docs-scaffold: documentation SSOT scaffold, checks, deprecation, session journal.

Python 3.8+, standard library only. Every check is warn-only: `check` prints
findings and exits 0. Exit code 2 signals a usage or configuration error.

Commands (run from the project root, or pass --project):
  init --type embedded|standalone   create the scaffold and manifest
  check                             report gaps, stale sections, broken links, ...
  index                             regenerate INDEX.md, _generated/, .deprecated/README.md, locks
  new <kind> <name>                 unit | adr | investigation | review | release | test-run | change
  verify <section-dir>...           stamp sections as verified against the current commit
  deprecate <path> --reason ...     preserve a spec in .deprecated/ (--keep copies before an edit)
  session start|log|sync|resync|show   append-only session journal in the ignore dir
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

SCHEMA = 1
SCAFFOLD_TYPES = ("embedded", "standalone")
LIVE_DIRS = ("10-context", "20-architecture", "30-units", "40-verification",
             "50-operations", "60-decisions", "70-work", "80-guides", "90-meta")
TOP_DIRS = LIVE_DIRS + ("_generated", ".deprecated")
TOP_FILES = ("README.md", "INDEX.md", "glossary.md")
STATUSES = ("draft", "approved", "todo", "n/a", "closed")
DOC_TYPES = ("readme", "section", "glossary", "conventions", "overview", "requirements",
             "nfr", "constraints", "architecture", "data-model", "interface",
             "cross-cutting", "design", "detail", "test", "ops", "strategy",
             "environment", "deploy", "configuration", "runbook", "adr", "status",
             "investigation", "test-run", "review", "release", "guide")
DESIGN_TYPES = {"architecture", "data-model", "interface", "design", "detail"}
TEST_TYPES = {"test", "strategy", "test-run"}
WORK_KINDS = {"investigation": "investigations", "review": "reviews",
              "release": "releases", "test-run": "test-runs"}
TEST_LEVELS = ("unit", "integration", "system")
REQUIRED_FM = ("id", "type", "status", "owner", "summary")
ID_RE = re.compile(r"\b(?:REQ|NFR)-\d+\b")
LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+)\)")
CODE_RE = re.compile(r"```.*?```|`[^`\n]*`", re.S)
COMMENT_RE = re.compile(r"<!--.*?-->", re.S)
GEN_MARK = "<!-- Generated by docs_scaffold.py. Do not edit; run `docs_scaffold.py index`. -->"
CHAIN_RE = re.compile(r"(### [^\n]*(?:\n(?!<!-- chain )[^\n]*)*)\n"
                      r"<!-- chain prev=([0-9a-f]{16}) hash=([0-9a-f]{16}) -->")
GENESIS = "0" * 16
SYNC_START = "<!-- docs-scaffold:sync:start -->"
SYNC_END = "<!-- docs-scaffold:sync:end -->"


class UsageError(Exception):
    pass


# --------------------------------------------------------------------------
# Frontmatter: flat `key: value` lines; values may be scalars, quoted strings,
# inline lists `[a, b]` or inline maps `{k: v}`. No nesting beyond one level.
# --------------------------------------------------------------------------

def _split_flow(text):
    parts, buf, quoted, escaped = [], "", False, False
    for ch in text:
        if quoted:
            buf += ch
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                quoted = False
        elif ch == '"':
            quoted, buf = True, buf + ch
        elif ch == ",":
            parts.append(buf)
            buf = ""
        else:
            buf += ch
    parts.append(buf)
    return [p.strip() for p in parts if p.strip()]


def _scalar(text):
    text = text.strip()
    if text.startswith('"'):
        try:
            return json.loads(text)
        except ValueError:
            return text.strip('"')
    if len(text) >= 2 and text[0] == text[-1] == "'":
        return text[1:-1]
    return text


def parse_value(text):
    text = text.strip()
    if text.startswith("[") and text.endswith("]"):
        return [_scalar(p) for p in _split_flow(text[1:-1])]
    if text.startswith("{") and text.endswith("}"):
        out = {}
        for part in _split_flow(text[1:-1]):
            key, _, val = part.partition(":")
            out[key.strip()] = _scalar(val)
        return out
    return _scalar(text)


def dump_value(value):
    if isinstance(value, list):
        return "[" + ", ".join(dump_value(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k}: {dump_value(v)}" for k, v in value.items()) + "}"
    text = str(value)
    return text if re.fullmatch(r"[A-Za-z0-9_./@*+-]+", text) else json.dumps(text)


def split_doc(text):
    """Return (frontmatter dict or None, body)."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return None, text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            fm = {}
            for line in lines[1:i]:
                if line.strip() and not line.lstrip().startswith("#"):
                    key, sep, val = line.partition(":")
                    if sep:
                        fm[key.strip()] = parse_value(val)
            return fm, "\n".join(lines[i + 1:])
    return None, text


def set_frontmatter(text, key, value):
    line = f"{key}: {dump_value(value)}"
    lines = text.split("\n")
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                for j in range(1, i):
                    if lines[j].partition(":")[0].strip() == key:
                        lines[j] = line
                        return "\n".join(lines)
                lines.insert(i, line)
                return "\n".join(lines)
    return f"---\n{line}\n---\n\n{text}"


def render_doc(doc_id, doc_type, status, summary, body, **extra):
    fields = {"id": doc_id, "type": doc_type, "status": status, "owner": "unassigned",
              "summary": summary}
    fields.update(extra)
    head = "\n".join(f"{k}: {dump_value(v)}" for k, v in fields.items())
    return f"---\n{head}\n---\n\n{body.strip()}\n"


def default_id(rel):
    parts = [re.sub(r"^\d+-", "", p) for p in rel[:-3].split("/")]
    if parts[-1] == "README":
        parts = parts[:-1] or ["readme"]
    return ".".join(parts)


def is_empty(body):
    text = COMMENT_RE.sub("", body)
    return not any(l.strip() and not l.lstrip().startswith("#") for l in text.splitlines())


# --------------------------------------------------------------------------
# Project, documents, git
# --------------------------------------------------------------------------

class Doc:
    def __init__(self, path, rel, fm, body):
        self.path, self.rel, self.fm, self.body = path, rel, fm, body

    def get(self, key, default=""):
        return (self.fm or {}).get(key, default)


class Project:
    def __init__(self, project, manifest_path):
        self.project = project
        self.manifest_path = manifest_path
        try:
            self.m = json.loads(manifest_path.read_text(encoding="utf-8"))
        except ValueError as exc:
            raise UsageError(f"invalid manifest {manifest_path}: {exc}")
        for key in ("type", "docs_root", "changes_dir", "ignore_dir"):
            if key not in self.m:
                raise UsageError(f"manifest {manifest_path} is missing '{key}'")
        self.root = (project / self.m["docs_root"]).resolve()
        self.changes = (project / self.m["changes_dir"]).resolve()
        self.ignore = (project / self.m["ignore_dir"]).resolve()
        self.locks_path = self.root / "90-meta" / "locks.json"

    def rel(self, path):
        return Path(os.path.relpath(str(path), str(self.root))).as_posix()

    def prel(self, path):
        return Path(os.path.relpath(str(path), str(self.project))).as_posix()

    @property
    def standalone(self):
        return self.m["type"] == "standalone"


def is_under(path, base):
    try:
        Path(path).resolve().relative_to(Path(base).resolve())
        return True
    except ValueError:
        return False


def find_project(args):
    project = Path(args.project).resolve()
    candidates = [project / args.root] if args.root else (
        [project / "docs", project] + sorted(p for p in project.iterdir() if p.is_dir()))
    for base in candidates:
        manifest = base / "90-meta" / "manifest.json"
        if manifest.is_file():
            return Project(project, manifest)
    raise UsageError("no docs scaffold found (90-meta/manifest.json); run `init` first")


def git(cwd, *args):
    try:
        return subprocess.run(("git",) + args, cwd=str(cwd), capture_output=True, text=True)
    except (FileNotFoundError, NotADirectoryError):
        return None


def git_out(cwd, *args):
    r = git(cwd, *args)
    return r.stdout.strip() if r is not None and r.returncode == 0 else None


def in_git(cwd):
    return git_out(cwd, "rev-parse", "--is-inside-work-tree") == "true"


def is_ignored(cwd, rel):
    r = git(cwd, "check-ignore", "-q", rel)
    return r is not None and r.returncode == 0


def load_doc(proj, path):
    text = path.read_text(encoding="utf-8", errors="replace")
    fm, body = split_doc(text)
    return Doc(path, proj.rel(path), fm, body)


def live_docs(proj):
    paths = [proj.root / n for n in TOP_FILES if n != "INDEX.md" and (proj.root / n).is_file()]
    for d in LIVE_DIRS:
        if (proj.root / d).is_dir():
            paths += sorted((proj.root / d).rglob("*.md"))
    return [load_doc(proj, p) for p in paths if not is_under(p, proj.changes)]


def repo_dirs(proj):
    """Map repo name -> local path (None when unavailable). '' is the project itself."""
    out = {"": proj.project}
    for name, spec in (proj.m.get("repos") or {}).items():
        env = (spec or {}).get("path_env", "")
        path = os.environ.get(env, "")
        out[name] = Path(path) if path and Path(path).is_dir() else None
    return out


def split_source(proj, source):
    name, sep, rest = source.partition(":")
    if proj.standalone and sep and name in (proj.m.get("repos") or {}):
        return name, rest
    return "", source


def group_sources(proj, sources):
    groups = {}
    for s in sources:
        repo, path = split_source(proj, s)
        groups.setdefault(repo, []).append(path)
    return groups


def changed_since(cwd, commit, paths):
    specs = [f":(glob){p}" for p in paths]
    diff = git_out(cwd, "diff", "--relative", "--name-only", commit, "--", *specs) or ""
    new = git_out(cwd, "ls-files", "--others", "--exclude-standard", "--", *specs) or ""
    return sorted(set(diff.splitlines() + new.splitlines()) - {""})


def section_state(proj, doc):
    """Return (state, detail): none | unverified | ok | stale | unverifiable | error."""
    sources = doc.get("sources", [])
    sources = [sources] if isinstance(sources, str) and sources else sources or []
    if not sources:
        return "none", ""
    verified = doc.get("verified", {})
    verified = verified if isinstance(verified, dict) else {}
    dirs = repo_dirs(proj)
    stale = []
    for repo, paths in group_sources(proj, sources).items():
        cwd = dirs.get(repo)
        label = repo or "project"
        if cwd is None or not in_git(cwd):
            return "unverifiable", f"repo '{label}' is not available as a local git clone"
        commit = verified.get(repo) or verified.get("commit") or ""
        if not commit:
            return "unverified", "no verified commit recorded"
        if git_out(cwd, "cat-file", "-e", f"{commit}^{{commit}}") is None:
            return "error", f"verified commit {commit} not found in repo '{label}'"
        stale += [f"{repo + ':' if repo else ''}{f}" for f in changed_since(cwd, commit, paths)]
    if stale:
        more = f" (+{len(stale) - 5} more)" if len(stale) > 5 else ""
        return "stale", ", ".join(stale[:5]) + more
    return "ok", ""


# --------------------------------------------------------------------------
# Generated files and locks
# --------------------------------------------------------------------------

def esc(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def render_index(docs):
    rows = [f"| [{d.rel}]({d.rel}) | {esc(d.get('id', '?'))} | {esc(d.get('type', '?'))} | "
            f"{esc(d.get('status', '?'))} | {esc(d.get('summary', ''))} |"
            for d in sorted(docs, key=lambda d: d.rel)]
    return ("# Documentation Index\n\n" + GEN_MARK + "\n\n"
            "| Path | ID | Type | Status | Summary |\n|---|---|---|---|---|\n"
            + "\n".join(rows) + "\n")


def defined_ids(docs):
    ids = set()
    for d in docs:
        if d.get("type") in ("requirements", "nfr"):
            ids.update(ID_RE.findall(d.body))
    return ids


def trace_map(docs):
    out = {}
    for d in docs:
        traces = d.get("traces", [])
        for t in [traces] if isinstance(traces, str) else traces or []:
            out.setdefault(t, []).append(d)
    return out


def _natural(text):
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", text)]


def render_traceability(docs):
    ids = sorted(defined_ids(docs), key=_natural)
    traces = trace_map(docs)
    lines = ["# Traceability", "", GEN_MARK, ""]
    if not ids:
        return "\n".join(lines + ["_No requirement IDs defined yet._", ""])
    lines += ["| Requirement | Design | Test | Other |", "|---|---|---|---|"]
    for rid in ids:
        ds = traces.get(rid, [])
        cell = lambda pred: ", ".join(sorted(d.get("id", d.rel) for d in ds if pred(d))) or "-"
        lines.append(f"| {rid} | {cell(lambda d: d.get('type') in DESIGN_TYPES)} | "
                     f"{cell(lambda d: d.get('type') in TEST_TYPES)} | "
                     f"{cell(lambda d: d.get('type') not in DESIGN_TYPES | TEST_TYPES)} |")
    return "\n".join(lines) + "\n"


def render_deprecated(proj):
    base = proj.root / ".deprecated"
    rows = []
    for d in sorted(p for p in base.iterdir() if p.is_dir()) if base.is_dir() else []:
        info = {}
        for f in sorted(d.rglob("*.md")):
            fm, _ = split_doc(f.read_text(encoding="utf-8", errors="replace"))
            if fm and isinstance(fm.get("deprecated"), dict):
                info = fm["deprecated"]
                break
        rows.append(f"| [{d.name}]({d.name}/) | {esc(info.get('date', '?'))} | "
                    f"`{esc(info.get('from', '?'))}` | {esc(info.get('reason', '?'))} | "
                    f"{esc(info.get('superseded_by', '?'))} |")
    body = "\n".join(rows) if rows else "| - | - | - | - | - |"
    return ("# Deprecated Documents\n\n" + GEN_MARK + "\n\n"
            "Preserved, read-only copies of wrong, mistaken, or substantively changed specs. "
            "Live documents must not link here.\n\n"
            "| Folder | Date | From | Reason | Superseded by |\n|---|---|---|---|---|\n"
            + body + "\n")


def generated_files(proj, docs):
    return {
        proj.root / "INDEX.md": render_index(docs),
        proj.root / "_generated" / "traceability.md": render_traceability(docs),
        proj.root / ".deprecated" / "README.md": render_deprecated(proj),
    }


def lock_hash(path, adr=False):
    data = path.read_bytes()
    if adr:
        data = b"\n".join(l for l in data.split(b"\n") if not l.lstrip().startswith(b"superseded_by:"))
    return hashlib.sha256(data).hexdigest()


def lockables(proj, docs):
    """Map rel path -> is_adr for every file that must never change again."""
    out = {}
    dep = proj.root / ".deprecated"
    if dep.is_dir():
        for f in dep.rglob("*"):
            if f.is_file() and f != dep / "README.md":
                out[proj.rel(f)] = False
    for d in docs:
        if d.rel.startswith("70-work/") and d.get("status") == "closed" and d.path.name != "STATUS.md":
            out[d.rel] = False
        if d.rel.startswith("60-decisions/") and d.get("type") == "adr" and d.get("status") == "approved":
            out[d.rel] = True
    return out


def read_locks(proj):
    if not proj.locks_path.is_file():
        return {}
    try:
        return json.loads(proj.locks_path.read_text(encoding="utf-8"))
    except ValueError:
        return {}


def write_locks(proj, locks):
    proj.locks_path.parent.mkdir(parents=True, exist_ok=True)
    proj.locks_path.write_text(json.dumps(dict(sorted(locks.items())), indent=2) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------
# Session journal (append-only, hash-chained across all session files)
# --------------------------------------------------------------------------

def sessions_dir(proj):
    return proj.ignore / "sessions"


def session_files(d):
    """Session files in creation order: YYYYMMDD-HHMMSS, then -2, -3 suffixes."""
    def key(p):
        m = re.match(r"^(\d{8}-\d{6})(?:-(\d+))?$", p.stem)
        return (m.group(1), int(m.group(2) or 1)) if m else (p.stem, 0)
    return sorted(d.glob("*.md"), key=key) if d.is_dir() else []


def journal(proj):
    entries = []
    for f in session_files(sessions_dir(proj)):
        for m in CHAIN_RE.finditer(f.read_text(encoding="utf-8")):
            entries.append({"file": f, "body": m.group(1), "prev": m.group(2), "hash": m.group(3)})
    return entries


def entry_hash(prev, body):
    return hashlib.sha256((prev + "\n" + body).encode("utf-8")).hexdigest()[:16]


def verify_chain(entries):
    problems, expected = [], GENESIS
    for e in entries:
        title = f"{e['file'].name} '{e['body'].splitlines()[0][4:]}'"
        if e["prev"] != expected:
            problems.append(f"{title} does not follow the previous entry (entry deleted or reordered)")
        if entry_hash(e["prev"], e["body"]) != e["hash"]:
            problems.append(f"{title} was modified after it was written")
        expected = e["hash"]
    return problems


def now():
    return dt.datetime.now().astimezone().replace(microsecond=0)


def git_facts(proj):
    lines = []
    for name, cwd in repo_dirs(proj).items():
        label = f"repo {name}" if name else "head"
        if cwd is None or not in_git(cwd):
            lines.append(f"{label}: unavailable")
            continue
        head = git_out(cwd, "rev-parse", "--short", "HEAD") or "none"
        branch = git_out(cwd, "rev-parse", "--abbrev-ref", "HEAD") or "?"
        status = git_out(cwd, "-c", "color.status=false", "status", "--short",
                         "--untracked-files=all", "--", ".") or ""
        changed = [" ".join(l.split()) for l in status.splitlines() if l.strip()]
        more = f" (+{len(changed) - 40} more)" if len(changed) > 40 else ""
        lines.append(f"{label}: {head} on {branch}")
        if not name:
            lines.append("changed: " + ("; ".join(changed[:40]) + more if changed else "clean"))
    return lines


def append_entry(proj, kind, result, lines, new_file=False):
    d = sessions_dir(proj)
    d.mkdir(parents=True, exist_ok=True)
    entries = journal(proj)
    prev = entries[-1]["hash"] if entries else GENESIS
    files = session_files(d)
    if new_file or not files:
        stamp = now().strftime("%Y%m%d-%H%M%S")
        target, n = d / f"{stamp}.md", 1
        while target.exists():
            n += 1
            target = d / f"{stamp}-{n}.md"
        target.write_text(f"# Session {target.stem}\n\n", encoding="utf-8")
    else:
        target = files[-1]
    number = sum(1 for e in entries if e["file"] == target) + 1
    clean = [" / ".join(str(l).splitlines()) for l in lines]
    body = f"### {number:03d} | {now().isoformat()} | {kind} | {result}\n" + "\n".join(f"- {l}" for l in clean)
    with target.open("a", encoding="utf-8") as fh:
        fh.write(f"{body}\n<!-- chain prev={prev} hash={entry_hash(prev, body)} -->\n\n")
    return target, number


def last_head(entries):
    for e in reversed(entries):
        m = re.search(r"^- head: ([0-9a-f]{4,40})\b", e["body"], re.M)
        if m:
            return m.group(1)
    return None


def resync_lines(proj, entries):
    lines = []
    prev_head = last_head(entries)
    head = git_out(proj.project, "rev-parse", "--short", "HEAD")
    if prev_head and head and prev_head != head:
        log = git_out(proj.project, "log", "--oneline", f"{prev_head}..HEAD", "--", ".")
        commits = (log or "").splitlines()
        lines.append("commits since last entry: " + ("; ".join(commits[:20]) if commits else
                     "none touching this project") + (f" (+{len(commits) - 20} more)" if len(commits) > 20 else ""))
    elif prev_head:
        lines.append("commits since last entry: none")
    stale = [d.rel for d in live_docs(proj) if d.get("type") == "section" and section_state(proj, d)[0] == "stale"]
    lines.append("stale sections: " + (", ".join(stale) if stale else "none"))
    return lines


# --------------------------------------------------------------------------
# Checks (warn-only)
# --------------------------------------------------------------------------

def run_checks(proj):
    findings = []

    def add(sev, check, path, msg, hint=""):
        findings.append((sev, check, path, msg, hint))

    docs = live_docs(proj)
    root_rel = proj.prel(proj.root)

    # structure
    for name in TOP_FILES:
        if not (proj.root / name).is_file():
            add("warn", "structure", name, "missing top-level file", "run `index` or `init`")
    for name in TOP_DIRS:
        if not (proj.root / name).is_dir():
            add("warn", "structure", name + "/", "missing top-level folder", "recreate it")
    prefixes = {}
    for p in proj.root.iterdir():
        m = re.match(r"^(\d+)-", p.name)
        if p.is_dir() and m:
            prefixes.setdefault(m.group(1), []).append(p.name)
    for prefix, names in prefixes.items():
        if len(names) > 1:
            add("warn", "structure", ", ".join(sorted(names)), f"duplicate numeric prefix {prefix}", "renumber one folder")
    for d in docs:
        if d.rel.count("/") > 3:
            add("warn", "structure", d.rel, "deeper than three folders below the docs root", "flatten")

    # tracking
    if in_git(proj.project):
        if is_ignored(proj.project, f"{root_rel}/README.md"):
            add("error", "tracking", root_rel, "docs root is git-ignored; docs must be tracked", "fix .gitignore")
        if is_ignored(proj.project, f"{proj.prel(proj.changes)}/x/requirements.md"):
            add("error", "tracking", proj.prel(proj.changes), "changes dir is git-ignored; specs must be tracked", "fix .gitignore")
        if not is_ignored(proj.project, f"{proj.prel(proj.ignore)}/x"):
            add("warn", "tracking", proj.prel(proj.ignore), "ignore dir is not git-ignored", "add it to .gitignore")

    # frontmatter
    seen = {}
    for d in docs:
        if d.fm is None:
            add("warn", "frontmatter", d.rel, "missing frontmatter", "add id, type, status, owner, summary")
            continue
        for key in REQUIRED_FM:
            if not str(d.get(key, "")).strip():
                add("warn", "frontmatter", d.rel, f"missing '{key}'", "fill it in")
        if d.get("type") and d.get("type") not in DOC_TYPES:
            add("warn", "frontmatter", d.rel, f"unknown type '{d.get('type')}'", "see 90-meta/conventions.md")
        if d.get("status") and d.get("status") not in STATUSES:
            add("warn", "frontmatter", d.rel, f"unknown status '{d.get('status')}'", "use " + ", ".join(STATUSES))
        if d.get("id"):
            seen.setdefault(d.get("id"), []).append(d.rel)
    for doc_id, rels in seen.items():
        if len(rels) > 1:
            add("error", "duplicate-id", ", ".join(rels), f"id '{doc_id}' used more than once", "make ids unique")

    # gaps
    for d in docs:
        status = d.get("status")
        if status == "todo":
            add("info", "gap", d.rel, "status todo", "write it or mark n/a with na_reason")
        elif status == "n/a" and not str(d.get("na_reason", "")).strip():
            add("warn", "gap", d.rel, "status n/a without na_reason", "add na_reason")
        elif d.fm is not None and is_empty(d.body) and status != "n/a":
            add("warn", "gap", d.rel, "document has no content", "write it or set status todo")
    kinds = proj.m.get("unit_kinds") or {"module": ["design.md", "tests.md"]}
    units_dir = proj.root / "30-units"
    units = []
    for p in sorted(units_dir.iterdir()) if units_dir.is_dir() else []:
        if not p.is_dir():
            continue
        readme = p / "README.md"
        is_group = not readme.is_file() and any(c.is_dir() for c in p.iterdir())
        units += sorted(c for c in p.iterdir() if c.is_dir()) if is_group else [p]
    for u in units:
        readme = u / "README.md"
        if not readme.is_file():
            add("warn", "gap", proj.rel(u) + "/", "unit has no README.md", f"run `new unit {u.name}`")
            continue
        kind = load_doc(proj, readme).get("kind", "module")
        if kind not in kinds:
            add("warn", "gap", proj.rel(readme), f"unknown unit kind '{kind}'", "declare it in manifest unit_kinds")
            continue
        for name in kinds[kind]:
            if not (u / name).is_file():
                add("warn", "gap", proj.rel(u / name), "required document missing", "create it (status todo is fine)")

    # coverage and traces
    ids = defined_ids(docs)
    traces = trace_map(docs)
    for rid in sorted(ids, key=_natural):
        types = {d.get("type") for d in traces.get(rid, [])}
        if not types & DESIGN_TYPES:
            add("warn", "coverage", rid, "not traced by any design document", "add it to a design doc's traces")
        if not types & TEST_TYPES:
            add("warn", "coverage", rid, "not traced by any test document", "add it to a test doc's traces")
    for t, ds in traces.items():
        if ID_RE.fullmatch(t) and t not in ids:
            add("warn", "trace", ", ".join(d.rel for d in ds), f"traces unknown id {t}", "define it or fix the trace")

    # links
    dep_root = proj.root / ".deprecated"
    for d in docs:
        for _, target in LINK_RE.findall(CODE_RE.sub("", COMMENT_RE.sub("", d.body))):
            if re.match(r"^[a-z][a-z0-9+.-]*:", target, re.I) or target.startswith("#"):
                continue
            path = (d.path.parent / target.split("#")[0].replace("%20", " ")).resolve()
            if is_under(path, dep_root):
                add("error", "deprecated-link", d.rel, f"links into .deprecated/: {target}", "link the replacement instead")
            elif not path.exists():
                add("warn", "link", d.rel, f"broken link: {target}", "fix or remove it")

    # staleness and section size
    low, high = (proj.m.get("section_size") or [2, 10])[:2]
    for d in docs:
        if d.get("type") != "section":
            continue
        state, detail = section_state(proj, d)
        if state == "stale":
            add("warn", "stale", d.rel, "sources changed since verification: " + detail, "update the section, then `verify`")
        elif state == "unverified":
            add("warn", "stale", d.rel, "section has sources but was never verified", "review it, then `verify`")
        elif state == "unverifiable":
            add("warn", "stale", d.rel, "unverifiable: " + detail, "set the repo path env var")
        elif state == "error":
            add("error", "stale", d.rel, detail, "re-verify the section")
        count = sum(1 for f in d.path.parent.glob("*.md") if f.name != "README.md")
        if not low <= count <= high:
            add("warn", "section-size", d.rel, f"section holds {count} documents (expected {low}-{high})", "merge or split")

    # locks
    locks = read_locks(proj)
    lockable = lockables(proj, docs)
    for rel, digest in sorted(locks.items()):
        path = proj.root / rel
        if not path.is_file():
            add("error", "immutable", rel, "locked file was deleted or moved", "restore it from git")
        elif lock_hash(path, lockable.get(rel, rel.startswith("60-decisions/"))) != digest:
            add("error", "immutable", rel, "locked file was modified", "restore it; record changes in a new document")
    for rel in sorted(set(lockable) - set(locks)):
        add("warn", "immutable", rel, "closed record is not locked yet", "run `index`")

    # generated files
    for path, content in generated_files(proj, docs).items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            add("warn", "generated", proj.rel(path), "generated file is out of date", "run `index`")

    # session journal (local only)
    entries = journal(proj)
    for problem in verify_chain(entries):
        add("error", "journal", proj.prel(sessions_dir(proj)), problem, "journals are append-only; restore the file")
    status = proj.root / "70-work" / "STATUS.md"
    if status.is_file():
        m = re.search(r"journal: \S+ entry \d+ hash ([0-9a-f]{16})", status.read_text(encoding="utf-8"))
        if m and entries and m.group(1) not in {e["hash"] for e in entries}:
            add("error", "journal", "70-work/STATUS.md", "entry recorded at last sync is missing from the journal (truncated or replaced)", "restore the journal")
        elif m and not entries:
            add("info", "journal", proj.prel(sessions_dir(proj)), "no local journal on this machine", "run `session start`")
    return findings, docs


def print_findings(findings):
    order = {"error": 0, "warn": 1, "info": 2}
    for sev, check, path, msg, hint in sorted(findings, key=lambda f: (order[f[0]], f[1], f[2])):
        print(f"[{sev.upper():5}] {check:15} {path}: {msg}" + (f"  -> {hint}" if hint else ""))
    counts = {s: sum(1 for f in findings if f[0] == s) for s in order}
    summary = f"{counts['error']} error, {counts['warn']} warn, {counts['info']} info"
    print(f"\n{summary} (warn-only: exit code 0)")
    return summary


def write_health(proj, findings, summary):
    lines = [f"# Docs health ({now().isoformat()})", "", summary, ""]
    lines += [f"- [{s}] {c} `{p}`: {m}" + (f" (fix: {h})" if h else "") for s, c, p, m, h in findings]
    proj.ignore.mkdir(parents=True, exist_ok=True)
    (proj.ignore / "health.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------
# Templates
# --------------------------------------------------------------------------

SECTION_EXTRA = {"sources": [], "verified": {"commit": "", "date": ""}}

ROOT_README = """# Documentation

## Purpose
<!-- What this documentation covers and who reads it. -->

## Scope
<!-- In scope / out of scope. -->

## Folder map
| Folder | Holds |
|---|---|
| `10-context/` | Overview, requirements (REQ-n), non-functional requirements (NFR-n), constraints |
| `20-architecture/` | Whole-system structure, data model, interfaces, cross-cutting concerns |
| `30-units/` | One folder per module, app, or service |
| `40-verification/` | Test strategy and test environments |
| `50-operations/` | Deploy, configuration, runbooks |
| `60-decisions/` | Numbered decision records (immutable once approved) |
| `70-work/` | Dated work records (immutable once closed) and `STATUS.md` |
| `80-guides/` | Onboarding, how-tos, examples |
| `90-meta/` | Conventions, manifest, locks |
| `_generated/` | Machine-owned output; never edit |
| `.deprecated/` | Preserved wrong or superseded specs; never link here |

## Reading order
1. This file, then `glossary.md`.
2. `10-context/overview.md`, then `20-architecture/system.md`.
3. The unit folders you work on, then `70-work/STATUS.md`.

## Status legend
`draft` written, not reviewed. `approved` reviewed, current. `todo` known gap. `n/a` not applicable (with `na_reason`). `closed` finished work record (locked).
"""

CONVENTIONS = """# Documentation Conventions

## Rules
1. One fact, one home. Link instead of copying.
2. Docs and specs are tracked by version control. The ignore dir holds only temporary, local material: session journals and health reports.
3. `10-context/` to `50-operations/` describe the system as it is now. `60-decisions/` and `70-work/` are history and are locked once approved or closed.
4. Code-derived reference material is generated into `_generated/`, never written by hand.
5. Every live document starts with frontmatter: `id`, `type`, `status`, `owner`, `summary` (one line). Add `traces: [REQ-1]` when a document satisfies requirements.
6. A section is a folder of 2 to 10 related documents whose `README.md` has `type: section`, `sources` (code globs) and `verified` (commit and date). A section is stale when its sources change after the verified commit.
7. Wrong, mistaken, or substantively changed specs are preserved with `deprecate`, never deleted. Minor edits (typography, spelling, formatting, link repair) rely on version control history.
8. Every change to the codebase is appended to the session journal. Journal entries are never edited or deleted.

## Frontmatter syntax
Flat `key: value` lines. Values: plain scalars, quoted strings, inline lists `[a, b]`, inline maps `{k: v}`.

## Types
readme, section, glossary, conventions, overview, requirements, nfr, constraints, architecture, data-model, interface, cross-cutting, design, detail, test, ops, strategy, environment, deploy, configuration, runbook, adr, status, investigation, test-run, review, release, guide.

## Statuses
draft, approved, todo, n/a (requires `na_reason`), closed.

## Naming
- Work records: `YYYY-MM-DD-<slug>.md`; test runs: `YYYY-MM-DD-<unit|integration|system>-r<N>.md`.
- Decisions: `NNNN-<slug>.md`.
- Deprecated material: `.deprecated/YYYY-MM-DD-<slug>/`.
"""


def section_tmpl(rel, summary, body):
    return render_doc(default_id(rel), "section", "draft", summary, f"{body}\n\n{summary}", **SECTION_EXTRA)


def todo(rel, doc_type, summary, headings):
    return render_doc(default_id(rel), doc_type, "todo", summary,
                      "\n\n".join(f"## {h}" for h in headings))


def scaffold_files(proj):
    f = {
        "README.md": render_doc("readme", "readme", "draft", "Entry point: purpose, scope, folder map, reading order.", ROOT_README),
        "glossary.md": render_doc("glossary", "glossary", "todo", "Project terms, acronyms, and aliases.", "# Glossary\n\n| Term | Meaning |\n|---|---|"),
        "10-context/README.md": section_tmpl("10-context/README.md", "Why and what: overview, requirements, constraints.", "# Context"),
        "10-context/overview.md": todo("10-context/overview.md", "overview", "Vision, stakeholders, boundaries.", ["Vision", "Stakeholders", "Boundaries", "Out of scope"]),
        "10-context/requirements.md": todo("10-context/requirements.md", "requirements", "Functional requirements with stable REQ-n IDs.", ["Requirements"]),
        "10-context/nfr.md": todo("10-context/nfr.md", "nfr", "Non-functional requirements with stable NFR-n IDs.", ["Performance", "Security", "Availability"]),
        "10-context/constraints.md": todo("10-context/constraints.md", "constraints", "Regulatory, client, and technical constraints.", ["Constraints"]),
        "20-architecture/README.md": section_tmpl("20-architecture/README.md", "Whole-system structure.", "# Architecture"),
        "20-architecture/system.md": todo("20-architecture/system.md", "architecture", "Context and component view; how units relate.", ["Context", "Components", "Flows"]),
        "20-architecture/data-model.md": todo("20-architecture/data-model.md", "data-model", "Entities, relationships, data ownership.", ["Entities", "Relationships"]),
        "20-architecture/interfaces.md": todo("20-architecture/interfaces.md", "interface", "Contracts between units and external systems.", ["Internal", "External"]),
        "20-architecture/cross-cutting.md": todo("20-architecture/cross-cutting.md", "cross-cutting", "Errors, logging, auth, configuration.", ["Errors", "Logging", "Security"]),
        "30-units/README.md": render_doc("units", "readme", "draft", "Index of units (modules, apps, services).", "# Units\n\nCreate units with `docs_scaffold.py new unit <name>`."),
        "40-verification/README.md": section_tmpl("40-verification/README.md", "Test strategy and environments.", "# Verification"),
        "40-verification/strategy.md": todo("40-verification/strategy.md", "strategy", "Test levels (unit, integration, system) and what each checks.", ["Unit", "Integration", "System"]),
        "40-verification/environments.md": todo("40-verification/environments.md", "environment", "Test environments and test data.", ["Environments", "Test data"]),
        "50-operations/README.md": section_tmpl("50-operations/README.md", "Build, deploy, configure, recover.", "# Operations"),
        "50-operations/deploy.md": todo("50-operations/deploy.md", "deploy", "How to build and deploy.", ["Build", "Deploy", "Rollback"]),
        "50-operations/configuration.md": todo("50-operations/configuration.md", "configuration", "Configuration and environment variables (templates live outside the docs root).", ["Variables"]),
        "60-decisions/README.md": render_doc("decisions", "readme", "draft", "Numbered decision records.", "# Decisions\n\nCreate with `docs_scaffold.py new adr <slug>`. Approved records are locked; supersede them with a new record."),
        "70-work/README.md": render_doc("work", "readme", "draft", "Dated work records and the progress ledger.", "# Work Records\n\nCreate with `docs_scaffold.py new <investigation|review|release|test-run|change> <name>`. Closed records are locked."),
        "70-work/STATUS.md": render_doc("work.status", "status", "draft", "Single living progress ledger.",
                                        f"# Status\n\n## Current focus\n\n_Nothing recorded yet._\n\n## Next steps\n\n_Nothing recorded yet._\n\n## Last sync\n\n{SYNC_START}\n{SYNC_END}"),
        "80-guides/README.md": render_doc("guides", "readme", "draft", "Onboarding, how-tos, examples.", "# Guides\n\nOnboarding paths, how-to guides, and worked examples."),
        "90-meta/conventions.md": render_doc("meta.conventions", "conventions", "approved", "Rules for this documentation tree.", CONVENTIONS),
    }
    return f


UNIT_DOCS = {
    "design.md": ("design", "Structure: components, classes, sequences, states.", ["Structure", "Sequences", "States"]),
    "detail.md": ("detail", "Method-level logic where it is not obvious from code.", ["Details"]),
    "interfaces.md": ("interface", "Public contracts of this unit.", ["Provided", "Consumed"]),
    "tests.md": ("test", "What is tested at each level, with traces.", ["Unit", "Integration", "System"]),
    "ops.md": ("ops", "Configuration, runbook notes, failure modes.", ["Configuration", "Failure modes"]),
}

CHANGE_DOCS = {
    "requirements.md": "# Requirements Document\n\n## Introduction\n\n## Requirements\n",
    "design.md": "# Design Document\n\n## Overview\n\n## Architecture\n\n## Components and Interfaces\n\n## Data Models\n\n## Error Handling\n\n## Testing Strategy\n",
    "tasks.md": "# Implementation Plan\n\n- [ ] 1. First task\n",
}


# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

def write_new(path, content, created, skipped, base):
    rel = Path(os.path.relpath(str(path), str(base))).as_posix()
    if path.exists():
        skipped.append(rel)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    created.append(rel)


def cmd_init(args):
    project = Path(args.project).resolve()
    root = args.root or "docs"
    manifest_path = project / root / "90-meta" / "manifest.json"
    if manifest_path.exists():
        raise UsageError(f"already initialized: {manifest_path}")
    changes = args.changes_dir or (".kiro/specs" if args.type == "embedded"
                                   else (Path(root) / "70-work" / "changes").as_posix())
    manifest = {"schema": SCHEMA, "type": args.type, "docs_root": root, "changes_dir": changes,
                "ignore_dir": args.ignore_dir, "repos": {}, "section_size": [2, 10],
                "unit_kinds": {"module": ["design.md", "tests.md"]}}
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    proj = Project(project, manifest_path)
    created, skipped = [], []
    for rel, content in scaffold_files(proj).items():
        write_new(proj.root / rel, content, created, skipped, proj.root)
    for d in ("_generated", ".deprecated"):
        (proj.root / d).mkdir(parents=True, exist_ok=True)
    if proj.standalone:
        proj.changes.mkdir(parents=True, exist_ok=True)
    write_locks(proj, read_locks(proj))
    note = ensure_ignored(proj)
    ensure_ignore_scaffold(proj)
    cmd_index_proj(proj, quiet=True)
    print(f"Initialized {args.type} scaffold at {proj.prel(proj.root)}/ "
          f"(changes: {changes}, ignore: {args.ignore_dir}/)")
    print(f"  created {len(created)} files")
    for rel in skipped:
        print(f"  kept existing file (not overwritten): {rel}")
    if note:
        print(f"  {note}")
    return 0


IGNORE_README = """# Ignore dir (local, temporary, never committed)

| Path | Holds | Written by |
|---|---|---|
| `sessions/` | Append-only, hash-chained session journals, one file per session | `session start`, `log`, `resync`, `sync` |
| `health.md` | Latest `check` report | `check` |

Never edit or delete journal entries; `check` detects it. Documentation and specs never belong here.
"""


def ensure_ignore_scaffold(proj):
    (proj.ignore / "sessions").mkdir(parents=True, exist_ok=True)
    readme = proj.ignore / "README.md"
    if not readme.exists():
        readme.write_text(IGNORE_README, encoding="utf-8")


def ensure_ignored(proj):
    rel = proj.prel(proj.ignore)
    if not in_git(proj.project):
        return f"not a git repository: make sure {rel}/ is excluded from version control"
    if is_ignored(proj.project, f"{rel}/x"):
        return None
    gi = proj.project / ".gitignore"
    text = gi.read_text(encoding="utf-8") if gi.is_file() else ""
    sep = "" if not text or text.endswith("\n") else "\n"
    gi.write_text(text + sep + f"/{rel}/\n", encoding="utf-8")
    return f"added /{rel}/ to {proj.prel(gi)}"


def cmd_index_proj(proj, quiet=False):
    docs = live_docs(proj)
    for path, content in generated_files(proj, docs).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
    locks = read_locks(proj)
    added = []
    for rel, adr in lockables(proj, docs).items():
        if rel not in locks:
            locks[rel] = lock_hash(proj.root / rel, adr)
            added.append(rel)
    write_locks(proj, locks)
    if not quiet:
        print(f"Regenerated INDEX.md, _generated/traceability.md, .deprecated/README.md "
              f"({len(docs)} live documents); locked {len(added)} new files")
    return 0


def cmd_check(args):
    proj = find_project(args)
    findings, _ = run_checks(proj)
    summary = print_findings(findings)
    write_health(proj, findings, summary)
    print(f"Report: {proj.prel(proj.ignore / 'health.md')}")
    return 0


def cmd_new(args):
    proj = find_project(args)
    created, skipped = [], []
    today = dt.date.today().isoformat()
    slug = re.sub(r"[^a-z0-9]+", "-", args.name.lower()).strip("-")
    if not slug:
        raise UsageError("name must contain letters or digits")
    if args.kind == "unit":
        base = proj.root / "30-units" / (args.group or "") / slug
        kinds = proj.m.get("unit_kinds") or {}
        if args.unit_kind not in kinds:
            raise UsageError(f"unknown unit kind '{args.unit_kind}' (manifest unit_kinds: {', '.join(kinds)})")
        rel = proj.rel(base / "README.md")
        write_new(base / "README.md", render_doc(default_id(rel), "section", "draft",
                  f"Unit {slug}: purpose and responsibilities.", f"# {slug}\n\n## Purpose\n\n## Responsibilities\n\n## Code",
                  kind=args.unit_kind, **SECTION_EXTRA), created, skipped, proj.root)
        for name in kinds[args.unit_kind]:
            doc_type, summary, heads = UNIT_DOCS.get(name, ("design", "", ["Content"]))
            write_new(base / name, todo(proj.rel(base / name), doc_type, summary, heads), created, skipped, proj.root)
    elif args.kind == "adr":
        base = proj.root / "60-decisions"
        nums = [int(m.group(1)) for p in base.glob("*.md") for m in [re.match(r"^(\d{4})-", p.name)] if m]
        path = base / f"{(max(nums) + 1 if nums else 1):04d}-{slug}.md"
        write_new(path, render_doc(default_id(proj.rel(path)), "adr", "draft", f"Decision: {args.name}",
                  "# Decision\n\n## Context\n\n## Decision\n\n## Alternatives\n\n## Consequences",
                  superseded_by="none"), created, skipped, proj.root)
    elif args.kind == "change":
        base = proj.changes / slug
        for name, content in CHANGE_DOCS.items():
            write_new(base / name, content, created, skipped, proj.root)
    else:
        base = proj.root / "70-work" / WORK_KINDS[args.kind]
        if args.kind == "test-run":
            if slug not in TEST_LEVELS:
                raise UsageError(f"test-run name must be one of {', '.join(TEST_LEVELS)}")
            rounds = len(list(base.glob(f"*-{slug}-r*.md"))) if base.is_dir() else 0
            path = base / f"{today}-{slug}-r{rounds + 1}.md"
            heads = "# Test run\n\n## Scope\n\n## Environment\n\n## Results\n\n## Defects"
        else:
            path = base / f"{today}-{slug}.md"
            heads = f"# {args.name}\n\n## Goal\n\n## Findings\n\n## Outcome"
        write_new(path, render_doc(default_id(proj.rel(path)), args.kind, "draft", args.name, heads),
                  created, skipped, proj.root)
    for rel in created:
        print(f"created {rel}")
    for rel in skipped:
        print(f"exists, kept: {rel}")
    cmd_index_proj(proj, quiet=True)
    return 0


def cmd_verify(args):
    proj = find_project(args)
    today = dt.date.today().isoformat()
    for target in args.sections:
        path = Path(target)
        readme = (path if path.name == "README.md" else path / "README.md").resolve()
        if not readme.is_file():
            raise UsageError(f"no section README.md at {target}")
        doc = load_doc(proj, readme)
        if doc.get("type") != "section":
            raise UsageError(f"{target} is not a section (README type must be 'section')")
        sources = doc.get("sources", [])
        sources = [sources] if isinstance(sources, str) and sources else sources or []
        if not sources:
            raise UsageError(f"{target} has no sources; add code globs before verifying")
        verified = {}
        for repo, paths in group_sources(proj, sources).items():
            cwd = repo_dirs(proj).get(repo)
            if cwd is None or not in_git(cwd):
                raise UsageError(f"repo '{repo or 'project'}' is not available as a local git clone")
            dirty = git_out(cwd, "status", "--porcelain", "--", *[f":(glob){p}" for p in paths])
            if dirty:
                print(f"warning: {target}: uncommitted changes in sources are not covered by this stamp")
            verified[repo or "commit"] = git_out(cwd, "rev-parse", "--short", "HEAD")
        verified["date"] = today
        text = readme.read_text(encoding="utf-8")
        readme.write_text(set_frontmatter(text, "verified", verified), encoding="utf-8")
        print(f"verified {proj.rel(readme)}: {dump_value(verified)}")
    return 0


def cmd_deprecate(args):
    proj = find_project(args)
    src = Path(args.path).resolve()
    if not src.exists():
        raise UsageError(f"not found: {args.path}")
    dep_root = proj.root / ".deprecated"
    if is_under(src, dep_root):
        raise UsageError("already deprecated")
    if not (is_under(src, proj.root) or is_under(src, proj.changes)):
        raise UsageError("only documents under the docs root or the changes dir can be deprecated")
    docs = live_docs(proj)
    by_id = {d.get("id"): d for d in docs if d.get("id")}
    superseded = args.superseded_by
    if superseded is None:
        own = load_doc(proj, src).get("id") if src.is_file() else ""
        if args.keep and own:
            superseded = own
        else:
            raise UsageError("--superseded-by is required (an id, or 'none')")
    if superseded != "none" and superseded not in by_id and not args.keep:
        raise UsageError(f"--superseded-by '{superseded}' is not a live document id")
    today = dt.date.today().isoformat()
    slug = re.sub(r"[^a-z0-9]+", "-", (src.stem if src.is_file() else src.name).lower()).strip("-")
    dest, n = dep_root / f"{today}-{slug}", 1
    while dest.exists():
        n += 1
        dest = dep_root / f"{today}-{slug}-{n}"
    dest.mkdir(parents=True)
    origin = proj.prel(src)
    if src.is_file():
        (shutil.copy2 if args.keep else shutil.move)(str(src), str(dest / src.name))
    elif args.keep:
        shutil.copytree(str(src), str(dest), dirs_exist_ok=True)
    else:
        for child in list(src.iterdir()):
            shutil.move(str(child), str(dest / child.name))
        src.rmdir()
    stamp = {"date": today, "from": origin, "reason": args.reason, "superseded_by": superseded}
    for md in sorted(dest.rglob("*.md")):
        md.write_text(set_frontmatter(md.read_text(encoding="utf-8"), "deprecated", stamp), encoding="utf-8")
    locks = read_locks(proj)
    for f in dest.rglob("*"):
        if f.is_file():
            locks[proj.rel(f)] = lock_hash(f)
    write_locks(proj, locks)
    rewritten, removed = (0, []) if args.keep else relink(proj, src, by_id.get(superseded))
    cmd_index_proj(proj, quiet=True)
    print(f"deprecated {origin} -> {proj.prel(dest)} ({'copied, original kept for editing' if args.keep else 'moved'})")
    if rewritten:
        print(f"  relinked {rewritten} links to {superseded}")
    for item in removed:
        print(f"  removed link (no replacement): {item}")
    return 0


def relink(proj, old, replacement):
    """Point live links at `old` to the replacement doc, or drop them."""
    count, removed = 0, []
    paths = [d.path for d in live_docs(proj)]
    if proj.changes.is_dir():
        paths += sorted(proj.changes.rglob("*.md"))
    for path in paths:
        text = path.read_text(encoding="utf-8")

        def fix(m):
            nonlocal count
            target = m.group(2)
            if re.match(r"^[a-z][a-z0-9+.-]*:", target, re.I) or target.startswith("#"):
                return m.group(0)
            resolved = (path.parent / target.split("#")[0]).resolve()
            if resolved != old and not is_under(resolved, old):
                return m.group(0)
            if replacement is not None and replacement.path.exists():
                count += 1
                new = Path(os.path.relpath(str(replacement.path), str(path.parent))).as_posix()
                return f"[{m.group(1)}]({new})"
            removed.append(f"{proj.prel(path)}: {target}")
            return m.group(1)

        new_text = LINK_RE.sub(fix, text)
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
    return count, removed


def update_status(proj, lines):
    path = proj.root / "70-work" / "STATUS.md"
    text = path.read_text(encoding="utf-8") if path.is_file() else scaffold_files(proj)["70-work/STATUS.md"]
    block = f"{SYNC_START}\n" + "\n".join(f"- {l}" for l in lines) + f"\n{SYNC_END}"
    if SYNC_START in text and SYNC_END in text:
        text = re.sub(re.escape(SYNC_START) + r".*?" + re.escape(SYNC_END), lambda _: block, text, flags=re.S)
    else:
        text = text.rstrip("\n") + f"\n\n## Last sync\n\n{block}\n"
    path.write_text(text, encoding="utf-8")


def cmd_session(args):
    proj = find_project(args)
    entries = journal(proj)
    problems = verify_chain(entries)
    for p in problems:
        print(f"[ERROR] journal: {p}")
    if args.action == "show":
        for e in entries[-args.n:]:
            print(f"[{e['file'].name}]\n{e['body']}\n")
        print(f"{len(entries)} entries; chain {'BROKEN' if problems else 'intact'}")
        return 0
    if args.action == "start":
        ensure_ignore_scaffold(proj)
        if entries:
            print("Previous entries:")
            for e in entries[-args.n:]:
                print(f"[{e['file'].name}]\n{e['body']}\n")
        lines = git_facts(proj)
        if args.goal:
            lines.append(f"goal: {args.goal}")
        if entries:
            lines.append(f"previous: {entries[-1]['file'].name} hash {entries[-1]['hash']}")
        lines += resync_lines(proj, entries)
        target, number = append_entry(proj, "start", "info", lines, new_file=True)
    elif args.action == "log":
        if not entries:
            raise UsageError("no session journal yet; run `session start` first")
        if not args.what:
            raise UsageError("session log requires --action")
        lines = git_facts(proj) + [f"action: {args.what}"]
        if args.note:
            lines.append(f"note: {args.note}")
        target, number = append_entry(proj, "log", args.result, lines)
    elif args.action == "resync":
        if not entries:
            raise UsageError("no session journal yet; run `session start` first")
        target, number = append_entry(proj, "resync", "info", git_facts(proj) + resync_lines(proj, entries))
    else:  # sync
        if not entries:
            raise UsageError("no session journal yet; run `session start` first")
        findings, _ = run_checks(proj)
        counts = {s: sum(1 for f in findings if f[0] == s) for s in ("error", "warn", "info")}
        health = f"{counts['error']} error, {counts['warn']} warn, {counts['info']} info"
        target, number = append_entry(proj, "sync", "info", git_facts(proj) + [f"health: {health}"]
                                      + ([f"note: {args.note}"] if args.note else []))
        last = journal(proj)[-1]
        head = git_out(proj.project, "rev-parse", "--short", "HEAD") or "none"
        update_status(proj, [f"last_sync: {now().isoformat()}", f"head: {head}",
                             f"journal: {last['file'].name} entry {number:03d} hash {last['hash']}",
                             f"health: {health}"])
    print(f"appended entry {number:03d} to {proj.prel(target)}")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--project", default=".", help="project root (default: current directory)")
    parser.add_argument("--root", default=None, help="docs root relative to the project (default: discovered)")
    # Accept the global options after the subcommand too (`init --type x --root .`).
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--project", default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    common.add_argument("--root", default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    sub = parser.add_subparsers(dest="cmd", required=True)
    _add = sub.add_parser
    sub.add_parser = lambda *a, **k: _add(*a, parents=[common], **k)

    p = sub.add_parser("init", help="create the scaffold")
    p.add_argument("--type", required=True, choices=SCAFFOLD_TYPES)
    p.add_argument("--changes-dir", default=None)
    p.add_argument("--ignore-dir", default="ignore")
    p.set_defaults(func=cmd_init)

    sub.add_parser("check", help="warn-only health check").set_defaults(func=cmd_check)
    sub.add_parser("index", help="regenerate generated files and locks").set_defaults(
        func=lambda a: cmd_index_proj(find_project(a)))

    p = sub.add_parser("new", help="create a unit, decision, work record, or change")
    p.add_argument("kind", choices=("unit", "adr", "change") + tuple(WORK_KINDS))
    p.add_argument("name")
    p.add_argument("--unit-kind", default="module")
    p.add_argument("--group", default=None, help="optional grouping folder for units")
    p.set_defaults(func=cmd_new)

    p = sub.add_parser("verify", help="stamp sections as verified at the current commit")
    p.add_argument("sections", nargs="+")
    p.set_defaults(func=cmd_verify)

    p = sub.add_parser("deprecate", help="preserve a spec in .deprecated/")
    p.add_argument("path")
    p.add_argument("--reason", required=True)
    p.add_argument("--superseded-by", default=None)
    p.add_argument("--keep", action="store_true", help="copy instead of move (before a substantive edit)")
    p.set_defaults(func=cmd_deprecate)

    p = sub.add_parser("session", help="append-only session journal")
    p.add_argument("action", choices=("start", "log", "sync", "resync", "show"))
    p.add_argument("--action", dest="what", default=None, help="what was done (session log)")
    p.add_argument("--result", default="ok", choices=("ok", "fail", "partial", "info"))
    p.add_argument("--note", default=None)
    p.add_argument("--goal", default=None)
    p.add_argument("-n", type=int, default=5, help="entries to print")
    p.set_defaults(func=cmd_session)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except UsageError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
