// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  orchestratorSidebar: [
    {
      type: "doc",
      id: "README",
      label: "Overview",
    },
    {
      type: "doc",
      id: "AGENT",
      label: "Agent Orchestrator",
    },
    {
      type: "category",
      label: "Skills",
      items: [
        {
          type: "autogenerated",
          dirName: "skills",
        },
      ],
    },
    {
      type: "category",
      label: "Workflows",
      items: [
        {
          type: "autogenerated",
          dirName: "workflows",
        },
      ],
    },
  ],
};

export default sidebars;
